/**
 * The error code registry from ERROR_HANDLING.md §4, in full.
 *
 * Clients branch on `code`, never on `message`, which makes every value here part of
 * the public API contract: adding a code is additive, changing or removing one is
 * breaking. Codes for features that have not landed are present because the registry
 * is normative — the document defines them, this file is the executable copy of it.
 */
export const ERROR_CODE = Object.freeze({
  // --- Authentication (401 / 403) ---
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  PASSWORD_REUSED: 'PASSWORD_REUSED',
  FORBIDDEN: 'FORBIDDEN',

  // --- Registration & users ---
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CITY_NOT_FOUND: 'CITY_NOT_FOUND',

  // --- Masters & moderation ---
  MASTER_NOT_FOUND: 'MASTER_NOT_FOUND',
  MASTER_NOT_APPROVED: 'MASTER_NOT_APPROVED',
  MASTER_UNAVAILABLE: 'MASTER_UNAVAILABLE',
  MASTER_NOT_READY_FOR_APPROVAL: 'MASTER_NOT_READY_FOR_APPROVAL',
  INVALID_APPROVAL_TRANSITION: 'INVALID_APPROVAL_TRANSITION',
  REASON_REQUIRED: 'REASON_REQUIRED',

  // --- Categories & services ---
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_NOT_LEAF: 'CATEGORY_NOT_LEAF',
  CATEGORY_DEPTH_EXCEEDED: 'CATEGORY_DEPTH_EXCEEDED',
  CATEGORY_IN_USE: 'CATEGORY_IN_USE',
  CATEGORY_SLUG_TAKEN: 'CATEGORY_SLUG_TAKEN',
  CATEGORY_INVALID_PARENT: 'CATEGORY_INVALID_PARENT',
  SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',
  SERVICE_INVALID: 'SERVICE_INVALID',
  SERVICE_CATEGORY_NOT_ATTACHED: 'SERVICE_CATEGORY_NOT_ATTACHED',

  // --- Scheduling ---
  SCHEDULE_OVERLAP: 'SCHEDULE_OVERLAP',
  INVALID_TIME_RANGE: 'INVALID_TIME_RANGE',
  EXCEPTION_ALREADY_EXISTS: 'EXCEPTION_ALREADY_EXISTS',
  DATE_RANGE_TOO_LARGE: 'DATE_RANGE_TOO_LARGE',

  // --- Bookings ---
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  SLOT_NOT_AVAILABLE: 'SLOT_NOT_AVAILABLE',
  SLOT_TOO_SOON: 'SLOT_TOO_SOON',
  BOOKING_OVERLAP: 'BOOKING_OVERLAP',
  CLIENT_SLOT_CONFLICT: 'CLIENT_SLOT_CONFLICT',
  TOO_MANY_PENDING_BOOKINGS: 'TOO_MANY_PENDING_BOOKINGS',
  ILLEGAL_BOOKING_TRANSITION: 'ILLEGAL_BOOKING_TRANSITION',
  TOO_EARLY_TO_START: 'TOO_EARLY_TO_START',
  BOOKING_NOT_COMPLETED: 'BOOKING_NOT_COMPLETED',

  // --- Reviews ---
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_WINDOW_CLOSED: 'REVIEW_WINDOW_CLOSED',
  REVIEW_EDIT_WINDOW_CLOSED: 'REVIEW_EDIT_WINDOW_CLOSED',
  REPLY_ALREADY_EXISTS: 'REPLY_ALREADY_EXISTS',

  // --- Files & chat ---
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  INVALID_FILE: 'INVALID_FILE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_MIME_TYPE: 'UNSUPPORTED_MIME_TYPE',
  FILE_NOT_CONFIRMED: 'FILE_NOT_CONFIRMED',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  NO_SHARED_BOOKING: 'NO_SHARED_BOOKING',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',

  // --- Banners ---
  BANNER_NOT_FOUND: 'BANNER_NOT_FOUND',

  // --- Generic ---
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_REFERENCE: 'INVALID_REFERENCE',
  CONFLICT: 'CONFLICT',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const);

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
