/** Data for `masters.seed.ts` — kept separate to keep that file under the 300-line cap. */
export const DEMO_MASTERS = [
  {
    slug: 'plumbing',
    email: 'marcus.vance@ustogo.tj',
    phone: '+992901111111',
    firstName: 'Marcus',
    lastName: 'Vance',
    displayName: 'Marcus Vance',
    city: 'Dushanbe',
    years: 15,
    bio: 'Specialist in trenchless pipe repair, tankless water heater installations and high-pressure sewer drain jetting.',
    price: 250,
    duration: 90,
    title: 'Emergency Pipe & Leak Repair',
  },
  {
    slug: 'electrical',
    email: 'alex.morgan@ustogo.tj',
    phone: '+992902222222',
    firstName: 'Alex',
    lastName: 'Morgan',
    displayName: 'Alex Morgan',
    city: 'Dushanbe',
    years: 12,
    bio: 'Licensed master electrician: residential rewiring, smart breaker panel upgrades and emergency troubleshooting.',
    price: 300,
    duration: 120,
    title: 'Smart Panel Upgrade & Wiring',
  },
  {
    slug: 'ac-repair',
    email: 'robert.miller@ustogo.tj',
    phone: '+992903333333',
    firstName: 'Robert',
    lastName: 'Miller',
    displayName: 'Robert Miller',
    city: 'Khujand',
    years: 11,
    bio: 'EPA-certified technician for multi-zone VRF systems and smart thermostat integration.',
    price: 280,
    duration: 90,
    title: 'AC Servicing & Freon Refill',
  },
  {
    slug: 'painting',
    email: 'elena.rostova@ustogo.tj',
    phone: '+992904444444',
    firstName: 'Elena',
    lastName: 'Rostova',
    displayName: 'Elena Rostova',
    city: 'Dushanbe',
    years: 9,
    bio: 'Venetian plaster finishes, limewash aesthetics and zero-VOC eco-friendly paints.',
    price: 200,
    duration: 240,
    title: 'Interior Wall Painting',
  },
  {
    slug: 'carpentry',
    email: 'daler.rahimov@ustogo.tj',
    phone: '+992905555555',
    firstName: 'Daler',
    lastName: 'Rahimov',
    displayName: 'Daler Rahimov',
    city: 'Bokhtar',
    years: 14,
    bio: 'Custom furniture, door fittings and wooden flooring for homes and offices.',
    price: 220,
    duration: 180,
    title: 'Custom Furniture & Cabinets',
  },
  {
    slug: 'cleaning',
    email: 'nigora.saidova@ustogo.tj',
    phone: '+992906666666',
    firstName: 'Nigora',
    lastName: 'Saidova',
    displayName: 'Nigora Saidova',
    city: 'Dushanbe',
    years: 6,
    bio: 'Full house deep cleaning, sofa shampooing and kitchen sanitization crews.',
    price: 150,
    duration: 180,
    title: 'Full House Deep Cleaning',
  },
  {
    slug: 'appliance-repair',
    email: 'farrukh.karimov@ustogo.tj',
    phone: '+992907777777',
    firstName: 'Farrukh',
    lastName: 'Karimov',
    displayName: 'Farrukh Karimov',
    city: 'Khujand',
    years: 10,
    bio: 'Washing machine, refrigerator and dishwasher repair with genuine parts.',
    price: 180,
    duration: 90,
    title: 'Washing Machine Repair',
  },
  {
    slug: 'masonry',
    email: 'shavkat.yusupov@ustogo.tj',
    phone: '+992908888888',
    firstName: 'Shavkat',
    lastName: 'Yusupov',
    displayName: 'Shavkat Yusupov',
    city: 'Kulob',
    years: 18,
    bio: 'Tile replacement, brickwork and marble polishing for residential and commercial sites.',
    price: 260,
    duration: 240,
    title: 'Tiling & Brickwork',
  },
  {
    slug: 'welding',
    email: 'jamshed.nazarov@ustogo.tj',
    phone: '+992909999999',
    firstName: 'Jamshed',
    lastName: 'Nazarov',
    displayName: 'Jamshed Nazarov',
    city: 'Dushanbe',
    years: 13,
    bio: 'Gate repair, metal railing fabrication and structural steel welding.',
    price: 240,
    duration: 150,
    title: 'Gate & Railing Fabrication',
  },
  {
    slug: 'roofing',
    email: 'bakhtiyor.tashkulov@ustogo.tj',
    phone: '+992910000000',
    firstName: 'Bakhtiyor',
    lastName: 'Tashkulov',
    displayName: 'Bakhtiyor Tashkulov',
    city: 'Khorog',
    years: 16,
    bio: 'Roof leak waterproofing, tile replacement and gutter repair.',
    price: 300,
    duration: 240,
    title: 'Roof Leak Waterproofing',
  },
  {
    slug: 'interior-design',
    email: 'sarah.jenkins@ustogo.tj',
    phone: '+992911111111',
    firstName: 'Sarah',
    lastName: 'Jenkins',
    displayName: 'Sarah Jenkins',
    city: 'Dushanbe',
    years: 10,
    bio: '3D space planning, color consultation and modular kitchen design for modern apartments.',
    price: 500,
    duration: 120,
    title: '3D Interior Design Consultation',
  },
  {
    slug: 'cctv-installer',
    email: 'david.chen@ustogo.tj',
    phone: '+992912222222',
    firstName: 'David',
    lastName: 'Chen',
    displayName: 'David Chen',
    city: 'Dushanbe',
    years: 8,
    bio: '4K PoE camera arrays, night-vision AI detection and encrypted NVR storage.',
    price: 350,
    duration: 180,
    title: 'CCTV & Alarm Installation',
  },
  {
    slug: 'networking',
    email: 'temur.aliev@ustogo.tj',
    phone: '+992913333333',
    firstName: 'Temur',
    lastName: 'Aliev',
    displayName: 'Temur Aliev',
    city: 'Khujand',
    years: 7,
    bio: 'Mesh Wi-Fi setup, fiber optic cabling and office network configuration.',
    price: 200,
    duration: 120,
    title: 'Mesh Wi-Fi & Network Setup',
  },
  {
    slug: 'locksmith',
    email: 'rustam.qodirov@ustogo.tj',
    phone: '+992914444444',
    firstName: 'Rustam',
    lastName: 'Qodirov',
    displayName: 'Rustam Qodirov',
    city: 'Dushanbe',
    years: 9,
    bio: 'Emergency door opening, deadbolt installation and key duplicating, 24/7.',
    price: 120,
    duration: 45,
    title: 'Emergency Lockout Service',
  },
  {
    slug: 'handyman',
    email: 'oleg.petrov@ustogo.tj',
    phone: '+992915555555',
    firstName: 'Oleg',
    lastName: 'Petrov',
    displayName: 'Oleg Petrov',
    city: 'Dushanbe',
    years: 5,
    bio: 'TV wall mounting, curtain hanging, shelf installation and odd jobs around the house.',
    price: 100,
    duration: 60,
    title: 'General Handyman Visit',
  },
] as const;
